"""empty message

Revision ID: cfa72026c95f
Revises: 456a945560f6
Create Date: 2021-06-24 18:43:00.001447

"""

# revision identifiers, used by Alembic.
revision = 'cfa72026c95f'
down_revision = '456a945560f6'

from alembic import op
import sqlalchemy as sa


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
